### ISSUE TITLE
iip-template

### ISSUE THREAD

**Issue by kehiy** [zurvan-lab/IPNN#9]
we need to write IIP template with a complete guide.

**Comment by eznix86** [comment]
Since it is a specification, we can get inspiration from W3C Template:
https://www.w3.org/People/Schepers/generic_template.html What do you think ?

**Comment by kehiy** [comment]
@eznix86 I agree, we can use the same template (with some small changes).

**Comment by eznix86** [comment]
What do you think about the version ? Should we do it Nostr way; Anyone can put their IIP-XX ? or We decide it ourself ?

Doing it the Nostr way means that others will keep track the version for us.
Doing it ourself, means we need to have a draft zone and a approved zone (where a number is assigned to it)

**Comment by kehiy** [comment]
we need to think about that, nostr way is freer.

**Comment by eznix86** [comment]
let's go with Nostr way to start, it is just rules, we can update it later.

**Comment by kehiy** [comment]
I agree.
